changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - wontfix
    authors:
      - dependabot
  categories:
    - title: 📚 Content Changes
      labels:
        - documentation
        - docs
        - guide
        - examples
        - tutorial
        - community
        - content
    - title: 🛠 Repository Improvements
      labels:
        - enhancement
        - automation
        - workflow
    - title: 🐛 Fixes
      labels:
        - bug
        - fix
        - hotfix
    - title: Other Changes
      labels:
        - "*"
