changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - wontfix
    authors:
      - dependabot
  categories:
    - title: 📚 Content
      labels:
        - content
    - title: 🛠 Maintenance
      labels:
        - meta
    - title: Other Changes
      labels:
        - "*"
