name: Auto Label Release PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Local test setup
        run: |
          if [ -n "$SETUP_SCRIPT" ] && [ -f "$SETUP_SCRIPT" ]; then
            bash "$SETUP_SCRIPT"
          fi

      - name: Check commit messages and add label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Get all commit messages in the PR
          commits=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].messageHeadline')

          # Check if any commit message starts with "release:"
          if echo "$commits" | grep -q "^release:"; then
            gh pr edit $PR_NUMBER --add-label "release"
          fi
