name: Check Markdown Links

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
  schedule:
    - cron: '0 2 * * *'  # Run nightly at 02:00

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.markdown-link-check.json'
          folder-path: '.'
          max-retry-count: 3
          retry-on: 429,500,502,503,504
