# This workflow ensures markdown files follow our style guide
# Logic:
# 1. Runs on every push and PR
# 2. Uses markdownlint-cli2 (same as local)
# 3. Attempts to auto-fix issues and commits them
# 4. If fixes aren't possible, fails the check
# 5. Also runs spell checking and code block validation

name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Fix markdown
        run: npm run fix:md
      - name: Check spelling
        run: npm run spell-check
      - name: Check code blocks
        run: npm run check-codeblocks
      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-fix markdown formatting"
          file_pattern: "*.md"
      - name: Check remaining issues
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: '**/*.md'
