# This workflow ensures markdown files follow our style guide
# Logic:
# 1. Runs on every push and PR
# 2. Uses markdownlint-cli2 (same as local)
# 3. Fails if any markdown files don't meet standards
# 4. Local pre-commit hook should catch these first

name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: '**/*.md'
